### ISSUE TITLE
Imputer Changes

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/dsbox-cleaning#15]
For the new_api branch:
+ Should provide default values for self.model and self.scorer.
+ Refactor Imputer into multiple classes
+ Remove model, scorer and strategy parameters from set_param() method

**Comment by luofanghao** [comment]
all 5 imputers are finished and tested through both my test scripts and TA2 system. If them looks good shall we merge them to master?

**Comment by kyao** [comment]
If they are compatible with the TA2 system, then let's merge them into master
