### ISSUE TITLE
D3M primitives entry point is not being used

### ISSUE THREAD

**Issue by raonilourenco** [usc-isi-i2/dsbox-cleaning#19]
As specified in the primitive interfaces repository: https://gitlab.datadrivendiscovery.org/d3m/primitive-interfaces#primitives-d3m-namespace

Python packages containing primitives should register them and expose them under the common
namespace by adding an entry like the following to package's setup.py:

entry_points = {
    'd3m.primitives': [
        'primitive_namespace.PrimitiveName = my_package.my_module:PrimitiveClassName',
    ],
},

This is helpful for TA2 systems to discover primitives "automatically".

**Comment by kyao** [comment]
Thank you for pointing this out. I will add entry points and release a new version later today.

**Comment by kyao** [comment]
Added d3m entry points. Please let us know if you have problems.

**Comment by raonilourenco** [comment]
I could successfully pull the primitives from d3m package. Thanks!
