### ISSUE TITLE
todo: add API to encode data label

### ISSUE THREAD

**Issue by luofanghao** [usc-isi-i2/dsbox-cleaning#2]
for data label, the encoder should do differently things such as: 
convert text to categorical data, rather than converting to indicator (in classification problem).

Could you add this API? thanks @rpedsel

**Comment by rpedsel** [comment]
Ok, sorry for the inconvenience...

**Comment by luofanghao** [comment]
Thanks! 
No worry, just normal development feedback :)
When you finish adding the API you can close this issue.

**Comment by rpedsel** [comment]
Done
