### ISSUE TITLE
Is it compatible with Python 3.6?

### ISSUE THREAD

**Issue by mitar** [usc-isi-i2/dsbox-cleaning#22]
In primitive's annotation I see only Python 3.5. Does this mean it is not compatible with Python 3.6 and we should not install it/use it with our system running on Python 3.6? If it is, maybe list both under `languages`?

**Comment by kyao** [comment]
It should be compatible with Python3.6 as well. I will listed it under both languages.

**Comment by mitar** [comment]
Great!
