### ISSUE TITLE
dsbox-datapreprocessing

### ISSUE THREAD

**Issue by remram44** [usc-isi-i2/dsbox-cleaning#27]
A package `dsbox-datapreprocessing` appears in the environment files. Was that a previous name of this package?

**Comment by kyao** [comment]
The repo for that package is here: https://github.com/usc-isi-i2/dsbox-profiling

**Comment by remram44** [comment]
So dsbox-profiling is dsbox-datapreprocessing and dsbox-cleaning is dsbox-datacleaning. You might want to rename the repos on GitHub to match, it doesn't break the Git checkouts as GitHub redirects.

**Comment by RqS** [comment]
Nor relevant anymore
