### ISSUE TITLE
UniformInt upper bound is non-inclusive

### ISSUE THREAD

**Issue by remram44** [usc-isi-i2/dsbox-cleaning#35]
That means that hyper-parameters such as 'verbose' cannot actually be set to any other value.

https://github.com/usc-isi-i2/dsbox-cleaning/blob/7b4336fe752cfcbaa06065651cacba32cf05ab15/dsbox/datapreprocessing/cleaner/mean.py#L26-L27

**Comment by kyao** [comment]
Good point!

**Comment by kyao** [comment]
Fixed in repo.
