### ISSUE TITLE
todo: no new column for binary categorical data

### ISSUE THREAD

**Issue by luofanghao** [usc-isi-i2/dsbox-cleaning#4]
for the current version if there is a column contains binary categorical data (say all data are true or false). the result dataFrame will generate two columns for the original column, which is totally redundant. For example for the o_38 dataset, the output dataFrame contains so many such columns. 

So I was wondering maybe it is better to make only one column output, for one binary categorical column? @kyao @rpedsel 

e.g:
original data:
TSH: true, false, true, false
current result:
TSH_true: 1,0,1,0
TSH_false:0,1,0,1

expected result:
TSH_true: 1,0,1,0

**Comment by rpedsel** [comment]
Thank you for reminding. I think to have only one column for binary data is reasonable, too.

**Comment by rpedsel** [comment]
Hi, I just found some problem...
If we make binary value column just one single column (w/ 0,1), when there are no missing value, it won't be a problem. When there are missing values in the column, I originally planned to just make an extra column for missing values, however, for the binary column, there are still missing cells there...(for the original encoder function, one-hot encoded columns only contain 0,1)
@kyao @luofanghao What should I do for the problem?
1. Still keep two columns (+missing value column) for binary column, as originally done.
2. Have single column for the binary column, make NaN cells -1 in the column (it's what pandas do when retrieving category codes (0,1,2...) ), also add extra column for missing values.
3. Have single column for the binary column, add missing value column, just leave missing values in the binary column.
4. Others...?

**Comment by rpedsel** [comment]
@kyao 
Fanghao and I just discussed a solution here:


if col.nunique == 1:
---- if missing: treat as single column, column_name = col_nan
---- else: (just a column with one value and no missing value)
elif col.nunique ==2:
---- if missing: keep original design: three columns: col_value1, col_value2, col_nan
---- else: treat as single column, column_name = col (original name)

Do you think it's a good solution?

**Comment by kyao** [comment]
I do not quit understand your proposal for the case when a column has a single unique value but with missing values. You are proposing a single column col_nan?

**Comment by rpedsel** [comment]
Yes, if a column only contains one unique value but has some cells missing, then just use one single column to represent it: 0 = non-missing, for the unique value in the column / 1 = missing.

**Comment by kyao** [comment]
It seems strange not to have a col_value column. But, if the goal is to avoid redundant columns the proposal makes sense.

Okay, let's go with the proposed solution.

**Comment by rpedsel** [comment]
Done
