### ISSUE TITLE
Profiler changes its input's metadata in-place

### ISSUE THREAD

**Issue by remram44** [usc-isi-i2/dsbox-cleaning#52]
The Profiler returns the same dataframe it got as input, but mutates its metadata in-place. This corrupts caches and messes up more complicated pipelines, and for example the case where I use multiple different profilers.

**Comment by kyao** [comment]
We can add a hyperparamter to specify just returning the new metadata instead of modifying the metadata of the dataframe. How do the other profilers work? Do they just return the metadata?

**Comment by mitar** [comment]
You shoud just copy the input dataframe and set new metadata on it and return that.

**Comment by kyao** [comment]
I thought about doing that. But, wouldn't copying the dataframe be expensive, especially for large datasets.

**Comment by mitar** [comment]
For now we are always copying in every primitive. We had a long discussion about this in the working group. See https://gitlab.com/datadrivendiscovery/d3m/issues/131 for more information (and related issues).

**Comment by RqS** [comment]
Made the change: https://github.com/usc-isi-i2/dsbox-cleaning/commit/02b086870b07977686f58079e30466dc1997282c
